### PR TITLE
add new model fields for AMA Questions - name, email

### LINKED ISSUE #9: Server Side AMA (3)
As a system, I need to organize the AMA content so that I can provide the data in a sensible way.

**ACCEPTANCE CRITERIA**

**Given** A request for Practice Page content
**When** I respond to the request
**Then** All questions and associated answers (and associated comments on those answers) should be available for query.
**And** Email is created and sent for all submitted questions

**NOTES**
- This will require updates to the data model
  - First Name, Last Name, Email - all non-required fields
- [Front-end work associated](https://github.com/openpracticelibrary/opl-fe/issues/22)

**BLOCKERS**
None

### PR DESCRIPTION
**Pull request by jameshbarton**
Resolves #9 

Adds new model fields for AMA Questions - firstName, lastName, email.  This PR is just for model changes.  It doesn't include email dispatch.

Sample GraphQL query for new fields attached
Screen Shot 2020-06-22 at 3 35 06 PM

### CODE REVIEW

**Comment by shaheinm** [comment]
We might want to consider default values for the first/last name field... either here, or in the frontend

**Comment by lallmon** [comment]
@shaheinm I have "Anonymous" and "User" for FN/LN on the front end now as default props if nothing is passed. But in the ContentAPI, what would empty values return in the query object?

**Comment by lallmon** [comment]
Also, a little disconnect is happening. The designs only have "Your name" as usable field, but we have them as separate keys.

**Comment by jameshbarton** [comment]
> Also, a little disconnect is happening. The designs only have "Your name" as usable field, but we have them as separate keys.

@lallmon @shaheinm - Thank you for the feedback.  I changed the Questions model to consolidate firstName and lastName into questionerName, and added Anonymous User as its default value.  I also changed the field name of email to be questionerEmail.  See sample GraphQL attached.

Screen Shot 2020-06-23 at 7 49 18 AM

**Pull request merged**
